#!/bin/bash

photo_directory=photos

function most_recent_photo {
    (
        cd $photo_directory
        bp=$(ls -t b_* | head -1)
        echo ${bp#b_}
    )
}

if [ $# -eq 0 ]
then
    photo=$(most_recent_photo)
else
    photo=$1
fi

if [ -z "$photo" ] || ! [ -f "$photo_directory/b_$photo" ] || ! [ -f "$photo_directory/1_$photo" ]
then
    echo "Not all specified photos exist:" $photo
    exit 1
fi



{
    echo "restart from $photo"
    echo $photo > .restart

    date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"
    ./binary
    date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"
}  2>&1 | tee output_restart.txt

# try to find last png
png=$(find  -path "./png/*.png" -printf "%T@ %P\n" | sort -n | tail -1 | awk '{print $2}') ;
if [ $? -eq 0 ]; then
    # found png
    tail -n 50 output_restart.txt | mail -A $png -a "From:simulations@arizona.edu" -s "restart run done" $2
else
    # no png found
    tail -n 50 output_restart.txt | mail -a "From:simulations@arizona.edu" -s "restart run done" $2
fi
